"Application":
  "WindowLibrary": "GLFW"
  "Renderer": "OpenGL"
  "SoundEngine": "OpenAL"
  "Name": "ExampleApplication"
"Window":
  "Size":
    - "1405"
    - "720"
  "Pos":
    - "-1687"
    - "522"